In [ ]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.naive_bayes import GaussianNB
from sklearn.naive_bayes import MultinomialNB

In [ ]:
file_test = pd.read_csv(r'/content/winequality-red.csv', sep = ";")
print("So luong phan tu trong tap du lieu", len(file_test)) #so luong phan tu
np.unique(file_test) #Liet ke cac gia tri khac nhau cua bien
file_test.value_counts()  #Liet ke so luong va cac gia tri khac nhau cua bien

So luong phan tu trong tap du lieu 1599


fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  free sulfur dioxide  total sulfur dioxide  density  pH    sulphates  alcohol  quality
7.5            0.510             0.02         1.7             0.084      13.0                 31.0                  0.99538  3.36  0.54       10.5     6          4
6.7            0.460             0.24         1.7             0.077      18.0                 34.0                  0.99480  3.39  0.60       10.6     6          4
7.2            0.360             0.46         2.1             0.074      24.0                 44.0                  0.99534  3.40  0.85       11.0     7          4
               0.695             0.13         2.0             0.076      12.0                 20.0                  0.99546  3.29  0.54       10.1     5          4
8.3            0.650             0.10         2.9             0.089      17.0                 40.0                  0.99803  3.29  0.55       9.5      5          3
                                                                                                                                                                 ..
7.5            0.430             0.30         2.2             0.062      6.0                  12.0                  0.99495  3.44  0.72       11.5     7          1
               0.420             0.32         2.7             0.067      7.0                  25.0                  0.99628  3.24  0.44       10.4     5          1
                                 0.31         1.6             0.080      15.0                 42.0                  0.99780  3.31  0.64       9.0      5          1
               0.410             0.15         3.7             0.104      29.0                 94.0                  0.99786  3.14  0.58       9.1      5          1
15.9           0.360             0.65         7.5             0.096      22.0                 71.0                  0.99760  2.98  0.84       14.9     5          1
Name: count, Length: 1359, dtype: int64

In [ ]:
x = file_test.drop('quality', axis=1)
y = file_test['quality']
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=1/5, random_state=42)
print("SL ptu trong tap test: ", len(x_test))
unique_test_labels = np.unique(y_test)
print("Cac nhan khac nhau trong tap test:", unique_test_labels)
print("SL tung nhan trong test test:")
print(y_test.value_counts())

SL ptu trong tap test:  320
Cac nhan khac nhau trong tap test: [3 4 5 6 7 8]
SL tung nhan trong test test:
quality
6    132
5    130
7     42
4     10
8      5
3      1
Name: count, dtype: int64


In [ ]:
Mohinh_KNN = KNeighborsClassifier(n_neighbors = 9)
Mohinh_KNN.fit(x_train, y_train)
y_pred = Mohinh_KNN.predict(x_test)
y_test
print("Accuracy is: ", accuracy_score(y_test, y_pred)*100)
print("Confusion matrix: \n", confusion_matrix(y_test, y_pred))

Accuracy is:  48.96810506566604
Confusion matrix: 
 [[  0   0   2   0   0   0]
 [  0   2   4  12   1   0]
 [  0   1 141  73   4   0]
 [  0   0  96 109  10   0]
 [  0   0  23  39   9   0]
 [  0   0   2   5   0   0]]


In [ ]:
print("Gia tri nhan thuc te va du doan cho 7 ptu dau tien trong tap test")
for i in range(7):
    print(f"Ptu {i + 1}: Nhan thuc te = {y_test.iloc[i]}, Nhan du doan = {y_pred[i]}")
y_test_7 = y_test.iloc[:7]
y_pred_7 = y_pred[:7]
accuracy_first_7 = accuracy_score(y_test_7, y_pred_7)
print("Do chinh xac tong the cho 7 phan tu dau tien", accuracy_first_7*100)


Gia tri nhan thuc te va du doan cho 7 ptu dau tien trong tap test
Ptu 1: Nhan thuc te = 6, Nhan du doan = 6
Ptu 2: Nhan thuc te = 5, Nhan du doan = 5
Ptu 3: Nhan thuc te = 6, Nhan du doan = 6
Ptu 4: Nhan thuc te = 5, Nhan du doan = 6
Ptu 5: Nhan thuc te = 6, Nhan du doan = 6
Ptu 6: Nhan thuc te = 5, Nhan du doan = 5
Ptu 7: Nhan thuc te = 5, Nhan du doan = 5
Do chinh xac tong the cho 7 phan tu dau tien 85.71428571428571


In [ ]:
model_nb = GaussianNB()
model_nb.fit(x_train, y_train)
y_pred_nb = model_nb.predict(x_test)
accuracy_nb = accuracy_score(y_test, y_pred_nb)
print("Do chinh xac tong the:", accuracy_nb * 100)
print("Do chinh xac cho tung phan lop:")
print(classification_report(y_test, y_pred_nb))


Do chinh xac tong the: 55.00000000000001
Do chinh xac cho tung phan lop:
              precision    recall  f1-score   support

           3       0.00      0.00      0.00         1
           4       0.17      0.10      0.12        10
           5       0.65      0.65      0.65       130
           6       0.53      0.52      0.52       132
           7       0.43      0.50      0.46        42
           8       0.00      0.00      0.00         5

    accuracy                           0.55       320
   macro avg       0.30      0.30      0.29       320
weighted avg       0.54      0.55      0.55       320



In [ ]:
accuracy_knn = accuracy_score(y_test, y_pred_knn)
accuracy_nb = accuracy_score(y_test, y_pred_nb)
if accuracy_knn > accuracy_nb:
    print("Mo hinh KNN co do chinh xac cao hon mo hinh Bayes: ", (accuracy_knn - accuracy_nb)*100)
else:
    print("Mo hinh Bayes co do chinh xac cao hon mo hinh KNN : ", (accuracy_nb - accuracy_knn)*100)


Mo hinh Bayes co do chinh xac cao hon mo hinh KNN :  5.816135084427771
